apiVersion: v1
kind: Deployment
metadata:
  name: simpleapi
  labels:
    app: simpleapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: simpleapi
        env: dev
    spec:
      containers:
        - name: simpleapi
          image: fra.ocir.io/jakobczyk/p-oraas-simple-api:1.0
          imagePullPolicy: Always
          ports:
          - name: simpleapi
            containerPort: 8080
            protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapi-service
  labels:
    app: simpleapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: simpleapi
