apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi
spec:
  selector:
    matchLabels:
      app: simpleapi
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - name: simpleapi
          image: fra.ocir.io/jakobczyk/p-oraas-simple-api:1.0
          imagePullPolicy: Always
          ports:
          - name: simpleapi
            containerPort: 8080
            protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
